export const protocolAccordionItems = [
  {
    title: "Prioritization Quorum",
    content: `A community can set this value that needs to be reached before a task can be claimed or contributed to. E.g. a proposal needs to have a >75% positive priority.`,
    isOpen: true,
  },
  {
    title: "Validation Quorum",
    content: `This is the minimum number of validations required for a task to be considered completed. It ensures that tasks are not marked as completed without sufficient review.`,
    isOpen: false,
  },
  {
    title: "Prioritization Period",
    content: `This is the time frame within which community members can prioritize tasks. It ensures that all tasks get a fair chance of being reviewed and prioritized.`,
    isOpen: false,
  },
  {
    title: "Contribution Period",
    content: `This is the time frame within which community members can contribute to tasks. It ensures that tasks are not left incomplete for long periods of time.`,
    isOpen: false,
  },
  {
    title: "Validation Period",
    content: `This is the time frame within which community members can validate completed tasks. It ensures that tasks are reviewed and validated in a timely manner.`,
    isOpen: false,
  },
];
export const rewardAccordionItems = [
  {
    title: "Proposal Reward",
    content: `A community can set this value that needs to be reached before a task can be claimed or contributed to. E.g. a proposal needs to have a >75% positive priority.`,
    isOpen: true,
  },
  {
    title: "Prioritization Reward",
    content: `This is the minimum number of validations required for a task to be considered completed. It ensures that tasks are not marked as completed without sufficient review.`,
    isOpen: false,
  },
  {
    title: "Validation Reward",
    content: `This is the time frame within which community members can prioritize tasks. It ensures that all tasks get a fair chance of being reviewed and prioritized.`,
    isOpen: false,
  },
  {
    title: "Claim-Stake-Amount",
    content: `This is the time frame within which community members can contribute to tasks. It ensures that tasks are not left incomplete for long periods of time.`,
    isOpen: false,
  },
];

export const rolesAndPermissions = [
  {
    fieldName: "communitySpecificSettings",
    title: "Set up community-specific settings.",
    isValidForAdmin: true,
    register_admin: "communitySpecificSettings.isValidForAdmin",
    isValidForMembers: false,
    register_member: "communitySpecificSettings.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "communitySpecificSettings.isValidForVetoPower",
  },
  {
    fieldName: "inviteOtherUsers",
    title: "Invite other users.",
    isValidForAdmin: true,
    register_admin: "inviteOtherUsers.isValidForAdmin",
    isValidForMembers: true,
    register_member: "inviteOtherUsers.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "inviteOtherUsers.isValidForVetoPower",
  },
  {
    fieldName: "approveMembersJoinRequest",
    title: "Approve member's join request.",
    isValidForAdmin: true,
    register_admin: "approveMembersJoinRequest.isValidForAdmin",
    isValidForMembers: false,
    register_member: "approveMembersJoinRequest.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "approveMembersJoinRequest.isValidForVetoPower",
  },
  {
    fieldName: "approveTaskProposal",
    title: "Approve a task proposal.",
    isValidForAdmin: true,
    register_admin: "approveTaskProposal.isValidForAdmin",
    isValidForMembers: false,
    register_member: "approveTaskProposal.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "approveTaskProposal.isValidForVetoPower",
  },
  {
    fieldName: "assignInitialMemberRolesAndPermissions",
    title: "Assign initial member roles and permissions.",
    isValidForAdmin: true,
    register_admin: "assignInitialMemberRolesAndPermissions.isValidForAdmin",
    isValidForMembers: false,
    register_member: "assignInitialMemberRolesAndPermissions.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power:
      "assignInitialMemberRolesAndPermissions.isValidForVetoPower",
  },
  {
    fieldName: "addOrRemoveMembers",
    title: "Add/remove members.",
    isValidForAdmin: true,
    register_admin: "addOrRemoveMembers.isValidForAdmin",
    isValidForMembers: false,
    register_member: "addOrRemoveMembers.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "addOrRemoveMembers.isValidForVetoPower",
  },
  {
    fieldName: "manageTaskSettings",
    title: "Manage task settings.",
    isValidForAdmin: true,
    register_admin: "manageTaskSettings.isValidForAdmin",
    isValidForMembers: false,
    register_member: "manageTaskSettings.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "manageTaskSettings.isValidForVetoPower",
  },
  {
    fieldName: "overseeCarrotDistribution",
    title:
      "Oversee carrot distribution, manage carrot-pot, and adjust reward settings.",
    isValidForAdmin: true,
    register_admin: "overseeCarrotDistribution.isValidForAdmin",
    isValidForMembers: false,
    register_member: "overseeCarrotDistribution.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "overseeCarrotDistribution.isValidForVetoPower",
  },
  {
    fieldName: "vetoInappropriateTasks",
    title: "Veto inappropriate tasks.",
    isValidForAdmin: false,
    register_admin: "vetoInappropriateTasks.isValidForAdmin",
    isValidForMembers: false,
    register_member: "vetoInappropriateTasks.isValidForMembers",
    isValidForVetoPower: true,
    register_veto_power: "vetoInappropriateTasks.isValidForVetoPower",
  },
  {
    fieldName: "viewOngoingTasks",
    title: "View ongoing tasks.",
    isValidForAdmin: true,
    register_admin: "viewOngoingTasks.isValidForAdmin",
    isValidForMembers: true,
    register_member: "viewOngoingTasks.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "viewOngoingTasks.isValidForVetoPower",
  },
  {
    fieldName: "reviewCommunityPerformance",
    title:
      "Review community performance, member engagement, and task success rates.",
    isValidForAdmin: true,
    register_admin: "reviewCommunityPerformance.isValidForAdmin",
    isValidForMembers: true,
    register_member: "reviewCommunityPerformance.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "reviewCommunityPerformance.isValidForVetoPower",
  },
  {
    fieldName: "postOnTaskDiscussion",
    title: "Post on Task Discussion.",
    isValidForAdmin: true,
    register_admin: "postOnTaskDiscussion.isValidForAdmin",
    isValidForMembers: true,
    register_member: "postOnTaskDiscussion.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "postOnTaskDiscussion.isValidForVetoPower",
  },
  {
    fieldName: "takesCarrotsToPrioritizeTasks",
    title: "Takes carrots to prioritize tasks.",
    isValidForAdmin: true,
    register_admin: "takesCarrotsToPrioritizeTasks.isValidForAdmin",
    isValidForMembers: true,
    register_member: "takesCarrotsToPrioritizeTasks.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "takesCarrotsToPrioritizeTasks.isValidForVetoPower",
  },
  {
    fieldName: "proposeNewTasks",
    title: "Propose new tasks.",
    isValidForAdmin: true,
    register_admin: "proposeNewTasks.isValidForAdmin",
    isValidForMembers: true,
    register_member: "proposeNewTasks.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "proposeNewTasks.isValidForVetoPower",
  },
  {
    fieldName: "contributeToTasks",
    title: "Contribute to tasks.",
    isValidForAdmin: true,
    register_admin: "contributeToTasks.isValidForAdmin",
    isValidForMembers: true,
    register_member: "contributeToTasks.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "contributeToTasks.isValidForVetoPower",
  },
  {
    fieldName: "participateInTaskValidation",
    title: "Participate in validation.",
    isValidForAdmin: true,
    register_admin: "participateInTaskValidation.isValidForAdmin",
    isValidForMembers: true,
    register_member: "participateInTaskValidation.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "participateInTaskValidation.isValidForVetoPower",
  },
  {
    fieldName: "trackRewards",
    title: "Track rewards and performance.",
    isValidForAdmin: true,
    register_admin: "trackRewards.isValidForAdmin",
    isValidForMembers: true,
    register_member: "trackRewards.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "trackRewards.isValidForVetoPower",
  },
  {
    fieldName: "adjustPersonalSettings",
    title: "Adjust personal settings and preferences.",
    isValidForAdmin: true,
    register_admin: "adjustPersonalSettings.isValidForAdmin",
    isValidForMembers: true,
    register_member: "adjustPersonalSettings.isValidForMembers",
    isValidForVetoPower: false,
    register_veto_power: "adjustPersonalSettings.isValidForVetoPower",
  },
];
